//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Visit_Manager.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  visits..
        /// </summary>
        public static string _visits {
            get {
                return ResourceManager.GetString("_visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add visit.
        /// </summary>
        public static string Add_visit {
            get {
                return ResourceManager.GetString("Add_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info..
        /// </summary>
        public static string Additional_info {
            get {
                return ResourceManager.GetString("Additional_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information.
        /// </summary>
        public static string Additional_information {
            get {
                return ResourceManager.GetString("Additional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Panel.
        /// </summary>
        public static string Admin_panel {
            get {
                return ResourceManager.GetString("Admin_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, cancel!.
        /// </summary>
        public static string Alert_btn_no_cancel {
            get {
                return ResourceManager.GetString("Alert_btn_no_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, change it!.
        /// </summary>
        public static string Alert_btn_yes_change {
            get {
                return ResourceManager.GetString("Alert_btn_yes_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, edit it!.
        /// </summary>
        public static string Alert_btn_yes_edit {
            get {
                return ResourceManager.GetString("Alert_btn_yes_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, remove it!.
        /// </summary>
        public static string Alert_btn_yes_remove {
            get {
                return ResourceManager.GetString("Alert_btn_yes_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danger!.
        /// </summary>
        public static string Alert_danger {
            get {
                return ResourceManager.GetString("Alert_danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Alert_success {
            get {
                return ResourceManager.GetString("Alert_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Alert_warning {
            get {
                return ResourceManager.GetString("Alert_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name.
        /// </summary>
        public static string Client_name {
            get {
                return ResourceManager.GetString("Client_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name &amp;.
        /// </summary>
        public static string Client_name_and {
            get {
                return ResourceManager.GetString("Client_name_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name &amp; surname.
        /// </summary>
        public static string Client_name_surname {
            get {
                return ResourceManager.GetString("Client_name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client surname.
        /// </summary>
        public static string Client_surname {
            get {
                return ResourceManager.GetString("Client_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client tel. number.
        /// </summary>
        public static string Client_tel_number {
            get {
                return ResourceManager.GetString("Client_tel_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this visit?.
        /// </summary>
        public static string Confirm_cancel {
            get {
                return ResourceManager.GetString("Confirm_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change your password?.
        /// </summary>
        public static string Confirm_change_password {
            get {
                return ResourceManager.GetString("Confirm_change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the data of this employee?.
        /// </summary>
        public static string Confirm_edit_employee {
            get {
                return ResourceManager.GetString("Confirm_edit_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the data of this type of visit..
        /// </summary>
        public static string Confirm_edit_visit_type {
            get {
                return ResourceManager.GetString("Confirm_edit_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this employee?.
        /// </summary>
        public static string Confirm_remove_employee {
            get {
                return ResourceManager.GetString("Confirm_remove_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove currently logged user? You will need to log in again..
        /// </summary>
        public static string Confirm_remove_employee_logg {
            get {
                return ResourceManager.GetString("Confirm_remove_employee_logg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this visit type?.
        /// </summary>
        public static string Confirm_remove_visit_type {
            get {
                return ResourceManager.GetString("Confirm_remove_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Confirm_title_are_you_sure {
            get {
                return ResourceManager.GetString("Confirm_title_are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost of visit.
        /// </summary>
        public static string Cost_of_visit {
            get {
                return ResourceManager.GetString("Cost_of_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist&apos;s visit..
        /// </summary>
        public static string Dentist_visit {
            get {
                return ResourceManager.GetString("Dentist_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to describe visit.
        /// </summary>
        public static string Describe_visit {
            get {
                return ResourceManager.GetString("Describe_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor:.
        /// </summary>
        public static string Doctor {
            get {
                return ResourceManager.GetString("Doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download excel.
        /// </summary>
        public static string Download_excel {
            get {
                return ResourceManager.GetString("Download_excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download pdf.
        /// </summary>
        public static string Download_pdf {
            get {
                return ResourceManager.GetString("Download_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor&apos;s edition.
        /// </summary>
        public static string Edit_employee {
            get {
                return ResourceManager.GetString("Edit_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/remove doctor.
        /// </summary>
        public static string Edit_remove_employee {
            get {
                return ResourceManager.GetString("Edit_remove_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit/remove visit type.
        /// </summary>
        public static string Edit_remove_visit_type {
            get {
                return ResourceManager.GetString("Edit_remove_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit visit.
        /// </summary>
        public static string Edit_visit {
            get {
                return ResourceManager.GetString("Edit_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the type of visit.
        /// </summary>
        public static string Edit_visit_type {
            get {
                return ResourceManager.GetString("Edit_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adress.
        /// </summary>
        public static string Email_adress {
            get {
                return ResourceManager.GetString("Email_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee removed!.
        /// </summary>
        public static string Employee_removed {
            get {
                return ResourceManager.GetString("Employee_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been properly removed. You must log in again to another account..
        /// </summary>
        public static string Employee_removed_login_again {
            get {
                return ResourceManager.GetString("Employee_removed_login_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit end.
        /// </summary>
        public static string End_time {
            get {
                return ResourceManager.GetString("End_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End visit.
        /// </summary>
        public static string End_visit {
            get {
                return ResourceManager.GetString("End_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error ! .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 404.
        /// </summary>
        public static string Error_404 {
            get {
                return ResourceManager.GetString("Error_404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Some Reason The Page You Requested Could Not Be Found On Our Server.
        /// </summary>
        public static string For_some_reason {
            get {
                return ResourceManager.GetString("For_some_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to visit page.
        /// </summary>
        public static string Go_to_visit {
            get {
                return ResourceManager.GetString("Go_to_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions, please call:.
        /// </summary>
        public static string If_you_have_any_questions {
            get {
                return ResourceManager.GetString("If_you_have_any_questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged as:.
        /// </summary>
        public static string Logged_as {
            get {
                return ResourceManager.GetString("Logged_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login entered is incorrect.
        /// </summary>
        public static string Login_incorrect {
            get {
                return ResourceManager.GetString("Login_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login must contain 3-25 characters.
        /// </summary>
        public static string Login_must_contain {
            get {
                return ResourceManager.GetString("Login_must_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login: name.surname.
        /// </summary>
        public static string Login_name_surname {
            get {
                return ResourceManager.GetString("Login_name_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login field is required.
        /// </summary>
        public static string Login_required {
            get {
                return ResourceManager.GetString("Login_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! This message was generated automatically by the website.
        /// </summary>
        public static string Message_was_generated_automatically {
            get {
                return ResourceManager.GetString("Message_was_generated_automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New doctor.
        /// </summary>
        public static string New_employee {
            get {
                return ResourceManager.GetString("New_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New visit.
        /// </summary>
        public static string New_visit {
            get {
                return ResourceManager.GetString("New_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New visit type.
        /// </summary>
        public static string New_visit_type {
            get {
                return ResourceManager.GetString("New_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display..
        /// </summary>
        public static string No_data_to_display {
            get {
                return ResourceManager.GetString("No_data_to_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments scheduled on the selected date..
        /// </summary>
        public static string No_visits_to_display {
            get {
                return ResourceManager.GetString("No_visits_to_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order visit.
        /// </summary>
        public static string Order_visit {
            get {
                return ResourceManager.GetString("Order_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other visit type.
        /// </summary>
        public static string Other_visit_type {
            get {
                return ResourceManager.GetString("Other_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address of our headquarters:.
        /// </summary>
        public static string Our_adress {
            get {
                return ResourceManager.GetString("Our_adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Page Not Found.
        /// </summary>
        public static string Page_not_found {
            get {
                return ResourceManager.GetString("Page_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        public static string Password_change {
            get {
                return ResourceManager.GetString("Password_change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Password_confirm {
            get {
                return ResourceManager.GetString("Password_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Password_current {
            get {
                return ResourceManager.GetString("Password_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is incorrect.
        /// </summary>
        public static string Password_incorrect {
            get {
                return ResourceManager.GetString("Password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contain 2-10 characters.
        /// </summary>
        public static string Password_must_contain {
            get {
                return ResourceManager.GetString("Password_must_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Password_new {
            get {
                return ResourceManager.GetString("Password_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Password_new_confirm {
            get {
                return ResourceManager.GetString("Password_new_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        public static string Password_required {
            get {
                return ResourceManager.GetString("Password_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not answer it..
        /// </summary>
        public static string Please_do_not_answer_it {
            get {
                return ResourceManager.GetString("Please_do_not_answer_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required_field {
            get {
                return ResourceManager.GetString("Required_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with information about the appointment has been sent..
        /// </summary>
        public static string Result_email_visit_added_correct {
            get {
                return ResourceManager.GetString("Result_email_visit_added_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem sending the email  about the appointment. Review the correctness of the entered data and try again..
        /// </summary>
        public static string Result_email_visit_added_error {
            get {
                return ResourceManager.GetString("Result_email_visit_added_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with information about the edited visit has been sent..
        /// </summary>
        public static string Result_email_visit_edited_correct {
            get {
                return ResourceManager.GetString("Result_email_visit_edited_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem sending the email  about the edited visit. Review the correctness of the entered data and try again..
        /// </summary>
        public static string Result_email_visit_edited_error {
            get {
                return ResourceManager.GetString("Result_email_visit_edited_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email with information about the canceling visit has been sent..
        /// </summary>
        public static string Result_email_visit_removed_correct {
            get {
                return ResourceManager.GetString("Result_email_visit_removed_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem sending the email  about the canceling visit. Review the correctness of the entered data and try again..
        /// </summary>
        public static string Result_email_visit_removed_error {
            get {
                return ResourceManager.GetString("Result_email_visit_removed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new employee has been successfully added..
        /// </summary>
        public static string Result_employee_added_correct {
            get {
                return ResourceManager.GetString("Result_employee_added_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem adding a new employee. Please check the correctness of the data and try again..
        /// </summary>
        public static string Result_employee_added_error {
            get {
                return ResourceManager.GetString("Result_employee_added_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An employee with this name and surname already exists. Change the data and try again..
        /// </summary>
        public static string Result_employee_already_exist_in_db {
            get {
                return ResourceManager.GetString("Result_employee_already_exist_in_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee data has been successfully changed..
        /// </summary>
        public static string Result_employee_edit_correct {
            get {
                return ResourceManager.GetString("Result_employee_edit_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with changing employee data. Please check the correctness of the data and try again..
        /// </summary>
        public static string Result_employee_edit_error {
            get {
                return ResourceManager.GetString("Result_employee_edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee has been successfully removed..
        /// </summary>
        public static string Result_employee_removed_correct {
            get {
                return ResourceManager.GetString("Result_employee_removed_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem removing the employee. Please try again later..
        /// </summary>
        public static string Result_employee_removed_error {
            get {
                return ResourceManager.GetString("Result_employee_removed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to download employee data..
        /// </summary>
        public static string Result_enable_to_get_employee {
            get {
                return ResourceManager.GetString("Result_enable_to_get_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to download visit type data.
        /// </summary>
        public static string Result_enable_to_get_visit_type {
            get {
                return ResourceManager.GetString("Result_enable_to_get_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes were made to the form..
        /// </summary>
        public static string Result_no_changes_in_form {
            get {
                return ResourceManager.GetString("Result_no_changes_in_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem changing the password. Change the data and try again..
        /// </summary>
        public static string Result_password_changing_error {
            get {
                return ResourceManager.GetString("Result_password_changing_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start of the visit must be an hour earlier than the end of the visit..
        /// </summary>
        public static string Result_start_visit_must_be_earlier {
            get {
                return ResourceManager.GetString("Result_start_visit_must_be_earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit has been added corret..
        /// </summary>
        public static string Result_visit_added_correct {
            get {
                return ResourceManager.GetString("Result_visit_added_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem adding the visit. Review the correctness of the entered data and try again..
        /// </summary>
        public static string Result_visit_added_error {
            get {
                return ResourceManager.GetString("Result_visit_added_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit data has been successfully changed..
        /// </summary>
        public static string Result_visit_edit_correct {
            get {
                return ResourceManager.GetString("Result_visit_edit_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with saving the visit to the database. Review the correctness of the entered data and try again..
        /// </summary>
        public static string Result_visit_edit_error {
            get {
                return ResourceManager.GetString("Result_visit_edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops ... it&apos;s impossible to arrange a visit at the times you chose. The time frame of the visit already includes another visit of the day. Choose different hours of the visit and try again..
        /// </summary>
        public static string Result_visit_frame_time_incorrect {
            get {
                return ResourceManager.GetString("Result_visit_frame_time_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit has been properly canceled..
        /// </summary>
        public static string Result_visit_removed_correct {
            get {
                return ResourceManager.GetString("Result_visit_removed_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem canceling the visit. Please try again later..
        /// </summary>
        public static string Result_visit_removed_error {
            get {
                return ResourceManager.GetString("Result_visit_removed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new type of visit has been successfully added..
        /// </summary>
        public static string Result_visit_type_added_correct {
            get {
                return ResourceManager.GetString("Result_visit_type_added_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem adding a new type of visit. Please check the correctness of the data and try again..
        /// </summary>
        public static string Result_visit_type_added_error {
            get {
                return ResourceManager.GetString("Result_visit_type_added_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A visit type with the same name already exists. Change the data and try again..
        /// </summary>
        public static string Result_visit_type_already_exist_in_db {
            get {
                return ResourceManager.GetString("Result_visit_type_already_exist_in_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the visit type has been changed..
        /// </summary>
        public static string Result_visit_type_edit_correct {
            get {
                return ResourceManager.GetString("Result_visit_type_edit_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with changing the name of the type of visit. Please try again later..
        /// </summary>
        public static string Result_visit_type_edit_error {
            get {
                return ResourceManager.GetString("Result_visit_type_edit_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of visit from the database has been successfully removed..
        /// </summary>
        public static string Result_visit_type_removed_correct {
            get {
                return ResourceManager.GetString("Result_visit_type_removed_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem removing the type of visit from the database. Please try again later..
        /// </summary>
        public static string Result_visit_type_removed_error {
            get {
                return ResourceManager.GetString("Result_visit_type_removed_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See you later!.
        /// </summary>
        public static string See_you_later {
            get {
                return ResourceManager.GetString("See_you_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the data range. Below statistics of.
        /// </summary>
        public static string Select_data_range {
            get {
                return ResourceManager.GetString("Select_data_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select doctor.
        /// </summary>
        public static string Select_doctor {
            get {
                return ResourceManager.GetString("Select_doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select visit type.
        /// </summary>
        public static string Select_visit_type {
            get {
                return ResourceManager.GetString("Select_visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired..
        /// </summary>
        public static string Session_expired {
            get {
                return ResourceManager.GetString("Session_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session has expired. You must log in again..
        /// </summary>
        public static string Session_expired_sign_in_again {
            get {
                return ResourceManager.GetString("Session_expired_sign_in_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Sign_In {
            get {
                return ResourceManager.GetString("Sign_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit begin.
        /// </summary>
        public static string Start_time {
            get {
                return ResourceManager.GetString("Start_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start visit.
        /// </summary>
        public static string Start_visit {
            get {
                return ResourceManager.GetString("Start_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street:.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to surname.
        /// </summary>
        public static string Surname2 {
            get {
                return ResourceManager.GetString("Surname2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel. number.
        /// </summary>
        public static string Tel_number {
            get {
                return ResourceManager.GetString("Tel_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string Telephone_number {
            get {
                return ResourceManager.GetString("Telephone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total visit cost.
        /// </summary>
        public static string Total_visit_cost {
            get {
                return ResourceManager.GetString("Total_visit_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of visits made.
        /// </summary>
        public static string Total_visit_count {
            get {
                return ResourceManager.GetString("Total_visit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unclassified.
        /// </summary>
        public static string Unclassified {
            get {
                return ResourceManager.GetString("Unclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unclassified type.
        /// </summary>
        public static string Unclassified_type {
            get {
                return ResourceManager.GetString("Unclassified_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit count.
        /// </summary>
        public static string Visit_count {
            get {
                return ResourceManager.GetString("Visit_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit date.
        /// </summary>
        public static string Visit_date {
            get {
                return ResourceManager.GetString("Visit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit describe.
        /// </summary>
        public static string Visit_describe {
            get {
                return ResourceManager.GetString("Visit_describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visit was correctly edited.
        /// </summary>
        public static string Visit_edited {
            get {
                return ResourceManager.GetString("Visit_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Manager.
        /// </summary>
        public static string Visit_manager {
            get {
                return ResourceManager.GetString("Visit_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit time.
        /// </summary>
        public static string Visit_time {
            get {
                return ResourceManager.GetString("Visit_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Visit_time1 {
            get {
                return ResourceManager.GetString("Visit_time1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Visit_time2 {
            get {
                return ResourceManager.GetString("Visit_time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of visit.
        /// </summary>
        public static string Visit_type {
            get {
                return ResourceManager.GetString("Visit_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits on:.
        /// </summary>
        public static string Visits_on {
            get {
                return ResourceManager.GetString("Visits_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The removal of the visit was canceled..
        /// </summary>
        public static string Warning_cancel_visit {
            get {
                return ResourceManager.GetString("Warning_cancel_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change has been canceled..
        /// </summary>
        public static string Warning_change_password_cancel {
            get {
                return ResourceManager.GetString("Warning_change_password_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edition of employee data was canceled..
        /// </summary>
        public static string Warning_edit_employee_cancel {
            get {
                return ResourceManager.GetString("Warning_edit_employee_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edition of type of visit was canceled..
        /// </summary>
        public static string Warning_edit_visit_type_cancel {
            get {
                return ResourceManager.GetString("Warning_edit_visit_type_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully. The website will be logged out in a moment. Sign in again..
        /// </summary>
        public static string Warning_password_changed {
            get {
                return ResourceManager.GetString("Warning_password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password and Confirm password fields must contain the same value..
        /// </summary>
        public static string Warning_password_the_same {
            get {
                return ResourceManager.GetString("Warning_password_the_same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The removal of this emloyee was canceled..
        /// </summary>
        public static string Warning_remove_employee_cancel {
            get {
                return ResourceManager.GetString("Warning_remove_employee_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The removal of this visit type was canceled..
        /// </summary>
        public static string Warning_remove_visit_type_cancel {
            get {
                return ResourceManager.GetString("Warning_remove_visit_type_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are pleased to inform you that we will meet soon :).
        /// </summary>
        public static string We_are_pleased_to_inform {
            get {
                return ResourceManager.GetString("We_are_pleased_to_inform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Visit manager !.
        /// </summary>
        public static string Welcome_info {
            get {
                return ResourceManager.GetString("Welcome_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to be able to use it..
        /// </summary>
        public static string Welcome_info_2nd_line {
            get {
                return ResourceManager.GetString("Welcome_info_2nd_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y..
        /// </summary>
        public static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have administrator rights. Some features may not be available..
        /// </summary>
        public static string You_are_not_admin {
            get {
                return ResourceManager.GetString("You_are_not_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dentist.
        /// </summary>
        public static string Your_dentist {
            get {
                return ResourceManager.GetString("Your_dentist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your visit:.
        /// </summary>
        public static string Your_visit {
            get {
                return ResourceManager.GetString("Your_visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your visit has been canceled..
        /// </summary>
        public static string Your_visit_canceled {
            get {
                return ResourceManager.GetString("Your_visit_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your visit has been edited..
        /// </summary>
        public static string Your_visit_edited {
            get {
                return ResourceManager.GetString("Your_visit_edited", resourceCulture);
            }
        }
    }
}
